routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::delete('/carts/empty','CartController@empty')->name('carts.empty');
Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController'); 
Route::resource('items', 'ItemController'); 
Route::resource('statuses', 'StatusController'); 
Route::resource('stocks', 'StockController'); 
Route::resource('carts', 'CartController'); 
Route::resource('transactions', 'TransactionController'); 

app/Stock.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    public function item()
    {
        return $this->belongsTo('App\Item');
    }
    public function transaction()
    {
    	return $this->belongsToMany(
    		'App\Stock','stock_transaction')
    		->withPivot('subtotal', 'price');
    }

    protected $fillable = [
        'item', 'serial', 'stat'];
}

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use App\Item;  
use App\Stock;
use Str; 
use Illuminate\Http\Request;



class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request, Stock $stock)
    {
        
        $filter = $request->query('item'); 
            if($filter){
               $stocks = Stock::all()->whereIn('item_id', $filter);
            } else {
                $stocks = Stock::all(); 
            }
        return view('stocks.index')
        ->with('stocks', $stocks)
        ->with('items', Item::all()); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Stock $stock)
    {
        $this->authorize('create',$stock);
        $items = Item::all(); 
        return view('stocks.create')->with('items', $items); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Stock $stock)
    {
        $this->authorize('view',$stock);
        $request->validate([
            'item_id' => 'required',
            'stat' => 'required',   
            'name' => 'required',
            'price' => 'required',  
        ]);  

        $stock = new Stock;
        $stock->item_id = $request->input('item_id');
        $stock->name = $request->input('name');
        $stock->price = $request->input('price');
        $stock->serial = Str::random(12); 
        $stock->stat = $request->input('stat');

        $stock->save(); 

        $item_stocks = Item::all(); 

       foreach ($item_stocks as $items) {
           $stocks = Stock::all()
            ->whereIn('item_id', $items->id)
            ->whereIn('stat', 'Available');
            $items->stock = count($stocks);
            $items->save();  
       }

        return redirect( route('stocks.index', ['stock' => $stock->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $items = Item::all(); 
        return view ('stocks.show')->with('items', $items)  ; 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function edit(Stock $stock)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Stock $stock)
    {
        $request->validate([
        
            'stat' => 'required',   
        ]);  
         
       $stock->stat = $request->input('stat'); 
      
    
       $stock->save();
       
       $item_stocks = Item::all(); 

       foreach ($item_stocks as $items) {
           $stocks = Stock::all()
            ->whereIn('item_id', $items->id)
            ->whereIn('stat', 'Available');
            $items->stock = count($stocks);
            $items->save();  
       }
       return redirect( route('stocks.index', ['stock' => $stock->id])); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stock $stock)
    {
        $stock->delete();

        $item_stocks = Item::all(); 

        foreach ($item_stocks as $items) {
            $stocks = Stock::all()
             ->whereIn('item_id', $items->id)
             ->whereIn('stat', 'Available');
             $items->stock = count($stocks);
             $items->save();  
        }
        return redirect( route('stocks.index'))->with('status', 'Stock Removed');

    }
}

resources/views/stocks/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card"> 
            @if ($errors->all())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h6 class="card-header">Create New Stock for Item</h6>
                <div class="card-body">

                <form action="{{ route('stocks.store')}}" method="post">
				@csrf

                    <!-- Item Name Select -->
                    <select name="item_id" id="item_id" class="custom-select" mb-2>
                   
					@foreach($items as $item)
						<option value="{{ $item->id }}" {{ old('item_id') == $item->id ? "selected":""}}>
						{{ $item->name }}
						</option>
					@endforeach
					</select>     
                    <hr> 
                     <!-- Name Field -->
                    <label for="name" hidden>Item Name</label>
                    <div> 
                    <input type="text" name="name" autocomplete="off" class="form-control" mb-2 placeholder="Enter Item Name" hidden>  
                    </div>

                    <!-- Price Field  -->
                    <label for="price">Item Price</label>
                    <div>
                    <input type="text" name="price" autocomplete="off" class="form-control" mb-2 placeholder="Enter Rental Fee" hidden>  
                    </div>       

                    <!-- Item Status  -->
                    <label for="status">Item Status</label>
                    <select name="stat" id="stat" class="form-control"> 
                        <option value="Available">Available </option> 
                        <option value="Not Available">Not Available </option> 
                    </select>

                    <div> 
                        <hr>    
                        <button type="submit" class="btn btn-warning mb-2">Generate Item Stock</button>
                    </div> 
								
                </form> 
                <div>
            </div>
        </div>
    </div>
</div> 
@endsection

resources/views/stocks/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card"> 
                     <!-- Start Card Header -->
                  <div class="card-header">{{ __('Survibes Stock List') }}</div> 

                    <!-- < Start Card Body  -->
                    <div class="card-body">

                    <!-- Filter bar  -->
                    <form action="" method="get">
                            <div class="row">
                                <!-- Filter Field   -->
                                    <div class="col"> 
                                        <select name="item" id="item" class="form-control">
                                            <option value="">All </option> 
                                            @foreach($items as $item)
                                                <option value="{{ $item->id}}">{{$item->name}}
                                                </option> 
                                            @endforeach
                                        </select>     
                                    </div> 
                    <!-- Filter Button   -->
                                <div class="col"> 
                                    <button class="btn btn-outline-primary">Stock Search</button> 
                                </div> 
                    </form> 
            
                    </div> 
                
                    <!-- Validation for Errors  -->
                    @if ($errors->all())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif  

                    <!-- Validation for Changes  -->
                    @if(Session::has('status'))
			        <div class="alert alert-success col-12">
			        	{{Session::get('status')}}
			        </div>
		            @endif
                    <hr> 
                    <!-- List of Stocks  -->
                    <div class="row"> 
                    @foreach($stocks as $stock)
                    <!-- Start of Card  -->
                        <div class="col-12 col-md-3 col-lg-3">
                            <div class="card">
                            <img src="/public/{{$item->image}}" alt="image unavailable" class="card-img-top">
                                <div class="card-body"> 
                                    <p class="card-text"><strong>{{ $stock->item->name}}</strong></p>

                                    <label for="serial"><small>Serial No.</small></label>
                                    <p class="card-text"><strong>{{ $stock->serial}}</strong></p>

                                    <label for="serial"><small>Status:</small></label>
                                    <p class="card-text"><strong>{{ $stock->stat}}</strong></p>
                                </div> 

                                <div class="card-footer">
                                <!-- Card Footer  -->
                                <!-- Request Button  -->
                                    <form action="{{ route('carts.update', ['cart'=>$stock->id])}}" method="post">
                                        @method('PUT')
                                        @csrf
                                        <button class="btn btn-outline-primary w-100 mb-2" {{($stock->stat == 'Not Available' ? 'disabled' : '')}}>Request</button>
                                     </form>

                                 <!-- Update Status  -->
                                    @can('isAdmin')
                                    <form action="{{ route('stocks.update', ['stock'=> $stock->id]) }}" method="post">
                                        @method('PUT')
                                        @csrf 
                                        <select name="stat" id="stat" class="form-control">
                                            <option disabled selected>Select Status</option> 
                                            <option value="Available">Available </option> 
                                            <option value="Not Available">Not Available </option> 
                                        </select>
                                        <button class="btn btn-outline-primary w-100 mb-2">Update Status</button>
                                    </form> 
                                <!-- Delete Stock  -->
                                    <form action="{{ route('stocks.destroy', ['stock'=> $stock->id])}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger w-100 mb-2">Delete Stock</button>
                                    </form> 

                                    @endcan
                                </div> 
                            </div>  
                        </div> 
                         <!-- End of Card  -->
                        @endforeach
                    </div>
                </div> 
                   
            </div>
        </div>
    </div> 
</div> 
@endsection

resources/views/stocks/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card"> 
                <div class="card-header">Item Show</div> 
                <div class="card-body">
                      
              
                    </div>
            </div> 
        </div> 
    </div> 
</div> 



@endsection