routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::delete('/carts/empty','CartController@empty')->name('carts.empty');
Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController'); 
Route::resource('items', 'ItemController'); 
Route::resource('statuses', 'StatusController'); 
Route::resource('stocks', 'StockController'); 
Route::resource('carts', 'CartController'); 
Route::resource('transactions', 'TransactionController'); 

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    public function item()
    {
        return $this->belongsTo('App\Item');
    }
    protected $fillable = [
        'quantity'];
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Stock; 
use Illuminate\Http\Request;
use Session; 
use App\Item;


class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        

        if(Session::has('cart'))  
        { 
        $stock_ids = array_keys(Session::get('cart'));
        $stocks = Stock::find($stock_ids);

        $total = 0; 
        foreach($stocks as $stock)
        {
            $stock->name = Session::get("cart.$stock->id"); 
            $stock->price =  $stock->price; 
            $total += $stock->price;  
            
        }
       
        return view('carts.index')
            ->with('stocks', $stocks)->with('stocks', $stocks)->with('total', $total); 
        } else {
            return view('carts.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function show(Cart $cart)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function edit(Cart $cart)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        $request->session()->put("cart.$id"); 

        return redirect(route('carts.index'))->with('status', 'Item added to Cart'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->session()->forget("cart.$id");

        if (count($request->session()->get('cart')) == 0) 
        {
            $request->session()->forget("cart");
        }
 
        return redirect( route('carts.index'))->with('status', 'Request Removed');
    }
    public function empty()
    {
       Session::forget('cart');
       return redirect( route('carts.index'))->with('status','Cart Cleared');
   }
}

resources/views/carts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
			<h5>Item Request form</h5>
		</div>

         <!-- Validation for Errors  -->
        @if ($errors->any())
	    <div class="alert alert-danger col-12">
	    	<ul>	
			    @foreach($errors->all() as $error)
			    <li>{{ $error }}</li>
			    @endforeach
		    </ul>
	    </div>
        @endif

         <!-- Validation for Changes  -->
         @if(Session::has('status'))
			<div class="alert alert-success col-12">
			    {{Session::get('status')}}
			</div>
		  @endif

        @if(Session::has('cart'))
        <div class="col-md-12">
            <div class="table table-responsive">
                <table class="table table-striped table-hover text-center">
                    <thead>
                        <th scope="col">Item Name</th>
                        <th scope="col">Serial No.</th>
                        <th scope="col">Rental Price</th>
                        <th scope="col">Request Actions</th>
                    </thead>
                    <tbody>
                    @foreach($stocks as $stock)
                       <tr>
                            <td>{{ $stock->item->name}}</td>
                            <td>{{ $stock->serial}}</td>
                            <td>  &#8369;{{number_format($stock->item->price,2)}}</td>
                            <td>
                                <!-- Item Delete  -->
                                <form action="{{ route('carts.destroy', ['cart'=> $stock->id])}}" method="post">
									@csrf
									@method('DELETE')
                                    <button class="btn btn-danger w-100 mb-2">Cancel</button>
                                </form> 
                            </td>
 
                        </tr> 
                        @endforeach
                        <tr>
                            <td colspan="3" class="text-right">Total</td>
							<td>&#8369; <span id="total">{{ number_format($total,2) }}</span></td>
                        </tr> 
                    </tbody>
                </table>     
            </div>
            <!-- Request Form Delete  -->
            <form action="{{ route('carts.empty')}}" method="post">	
				@csrf
				@method('DELETE')
	            <button type="submit" class="btn btn-dark">Delete Request Form</button>
            </form>
            @can('isLogged')
            <form action="{{ route('transactions.store')}}" method="post">																					
			@csrf
			<button class="btn btn-primary mt-2">Submit Request Form</button>
			</form>
            @endcan
        </div> 
        @else
            <div class="col-12">
               	<div class="alert alert-info">
               	Cart Empty
            </div>
        @endif 
    </div> 
</div>
@endsection 