routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::delete('/carts/empty','CartController@empty')->name('carts.empty');
Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController'); 
Route::resource('items', 'ItemController'); 
Route::resource('statuses', 'StatusController'); 
Route::resource('stocks', 'StockController'); 
Route::resource('carts', 'CartController'); 
Route::resource('transactions', 'TransactionController'); 

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
    public function stock()
    {
        return $this->hasMany('App\Stock');
    }
    public function transaction()
    {
    	return $this->belongsToMany(
    		'App\Item','item_transaction')
    		->withPivot('subtotal', 'price');
    }

    protected $fillable = [
        'name', 'price', 'image', 'brand', 'color', 'size', 'category_id'];
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Category; 
use App\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    public function index(Request $request, Item $item)
    {  
        // $this->authorize('view', $item); 
        $filter = $request->query('category'); 
            if($filter){
                $items = Item::all()->whereIn('category_id', $filter);
            } else {
                $items = Item::all(); 
            }
        return view('items.index')
            ->with('items', $items)
            ->with('categories', Category::all()); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Item $item)
    {
        $this->authorize('create',$item);
        $categories = Category::all(); 
        return view('items.create')
            ->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Item $item)
    {   
        
        $request->validate([
         'name' => 'required|string',
         'price' => 'numeric',
         'category_id' => 'required',
         'image' => 'required|image|max:5000',
         'color' => 'required',
         'brand' => 'required',
         'size' => 'required'
        ]);  
        
        $item = new Item;
        $item->name = $request->input('name');
        $item->price = $request->input('price'); 
        $item->stock = $request->input('stock'); 
        $item->category_id = $request->input('category_id');
        $item->color = $request->input('color');
        $item->brand = $request->input('brand');
        $item->size = $request->input('size');     
        $item->image = $request->image->store('public','public');
   
        $item->save(); 

        return redirect( route('items.index')); 

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('items.show')->with('item', $item); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $categories = Category::all();
        return view("items.edit", compact('item'))->with('categories', $categories); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $request->validate([
            'name' => 'required|string',
            'price' => 'numeric',
            'category_id' => 'required',
            'image' => 'required|image|max:5000',
            'color' => 'required',
            'brand' => 'required',
            'size' => 'required'
           ]);  
        
           $item->name = $request->input('name');
           $item->price = $request->input('price'); 
           $item->stock = $request->input('stock'); 
           $item->category_id = $request->input('category_id');
           $item->color = $request->input('color');
           $item->brand = $request->input('brand');
           $item->size = $request->input('size');  

           if($request->hasFile('image'))
           {
            $item->image = $request->image->store('items');
           }
           $item->save();
           
           $request->session()->flash('status', 'update successful'); 

          return redirect( route('items.edit',['item'=>$item->id]));   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect(route('items.index'))->with('status', 'Item is Deleted'); 
    }
}

resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> 

                    @if ($errors->all())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                     <form action="{{ route('items.store')}}" method="post" enctype="multipart/form-data">   
                        @csrf 
                              <!-- Start Card Header    -->
                            <div class="card-header">{{ __('Create New Item') }}</div>

                              <!-- Start Card Body     -->
                            <div class="card-body">

                                      <!-- Name Field     -->
                                     <div> 
                                    
                                        <input type="text" name="name" autocomplete="off" class="form-control" mb-2 placeholder="Enter Item Name" 
                                        value="{{  old('name')}}">  
                                        
                                    
                                    </div>
                                    <hr>  
                                      <!-- Price Field     -->
                                    <div>
                                        
                                        <input type="number" name="price" autocomplete="off" class="form-control" mb-2 placeholder="Enter Rental Fee"  
                                        value="{{ old('price')}}">  
                                       
                                    </div> 
                                    <hr> 
                                        <!-- Stock Field     -->
                                      <div>
                                    
                                        <input type="number" name="stock" id="stock" class="form-control mb-1" value="1" min="0" hidden>           
                     
                                    </div> 
                                    
                                      <!-- Category Field     -->
                                      <div>
                                        
                                        <select name="category_id" id="category_id" class="custom-select" mb-2>
                                            @foreach($categories as $category)
                                            <option value="{{ $category->id }}"{{ old('category_id') == $category->id ? "selected":""}}>
                                            {{ $category->name}}
                                            </option>
                                            @endforeach
                                        </select>
                                               
                                      
                                    </div>

                                    <hr>    
                                      <!-- Image Field     -->

                                    <input type="file" name="image" id="image" class="form-control-file" mb-2>
                                  
                                
                                    <hr> 
                                        <div class="row">   
                                                  <!-- Color Field     -->
                                                      <div class="col-4">
                                                    
                                                            <label for="color" class="row-md-1 col-form-label text-md-right ml-1">{{ ('Color') }}</label> 
                                                

                                                            <div class="col-12 w-100">
                                                                <select name="color" id="color" class="form-control">
                                                                    <option value="n/a">Not Available </option> 
                                                                    <option value="Blue">Blue </option> 
                                                                    <option value="Light Blue">Light Blue </option> 
                                                                    <option value="Dark Blue">Dark Blue </option> 
                                                                    <option value="Green">Green </option> 
                                                                    <option value="Magenta">Magenta </option> 
                                                                    <option value="Magenta">Red </option> 
                                                                    <option value="Yellow">Yellow </option> 
                                                                    <option value="Magenta">Violet </option> 
                                                                </select> 
                                                            </div> 
                                                    </div>         
                                                        
                                                
                                                  <!-- Brand Field     -->
                                                    
                                                  <div class="col-4">
                                                            <label for="brand" class="row-md-1 col-form-label text-md-right ml-1">{{ ('Brand') }}</label>    

                                                            <div class="col-12 w-100">
                                                                <select name="brand" id="brand" class="form-control"> 
                                                                <option value="Generic">Generic </option> 
                                                                    <option value="Amazon">Amazon </option> 
                                                                    <option value="Speedo">Speedo </option> 
                                                                    <option value="Copozz">Copozz </option> 
                                                                    <option value="Izod">Izod </option> 
                                                                    <option value="Columbia">Columbia </option> 
                                                                    <option value="Smaco">Smaco </option> 
                                                                    <option value="Atomic Aquatics">Atomic Aquatics </option> 
                                                                </select>
                                                            </div> 
                                                            
                                                        
                                                    </div>   
                                                
                                                  <!-- Size Field     -->
                                                

                                                  <div class="col-4">
                                                            <label for="size" class="row-md-1 col-form-label text-md-right ml-1">{{ ('Size') }}</label>  
                                                        
                                                            <div class="col-12 w-100">
                                                                <select name="size" id="size" class="form-control"> 
                                                                <option value="All">All </option> 
                                                                <option value="Adult">Adult </option> 
                                                                <option value="Kids">Kids </option> 
                                                                <option value="XL">XL </option> 
                                                                </select> 
                                                            </div> 
                                                            
                                                                
                                                </div>
                                                
                                            
                                        
                                        </div> 
                                    
                                            <br>    
                                          <button type="submit" class="btn btn-primary">Create New Item</button>      
                                    
                            </div>
                 </form> 
            </div> 
        </div> 
    </div>
</div> 

@endsection 

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-12 col-md-7 ">
            <div class="card"> 
                @if ($errors->all())
                    <div class="alert alert-danger">
                            <ul>
                                 @foreach ($errors->all() as $error)
                                     <li>{{ $error}}</li>
                                 @endforeach
                            </ul>
                    </div>
                @endif
                        <form action="{{ route('items.update', ['item'=>$item->id])}}" method="post" enctype="multipart/form-data">   
                            @csrf 
                            @method('PATCH')
                                <!-- Start Card Header -->
                                <div class="card-header">{{ __('Create New Item') }}</div>

                                <!-- Start Card Body -->
                                <div class="card-body">

                                        <!-- Name Field -->
                                        <div> 
                                        
                                            <input type="text" name="name" autocomplete="off" class="form-control" mb-2 placeholder="Enter Item Name" 
                                            value="{{ $item->name}}">  
                                            
                                        
                                        </div>
                                        <hr>  
                                        <!-- Price Field  -->
                                        <div>
                                            
                                            <input type="text" name="price" autocomplete="off" class="form-control" mb-2 placeholder="Enter Rental Fee"  
                                            value="{{ $item->price}}">  
                                        
                                        </div> 
                                        <hr>  

                                        <!-- Category Field  -->
                                        <div>
                                            
                                            <select name="category_id" id="category_id" class="custom-select" mb-2>
                                                <option value="{{$item->category_id}}">Choose Item Category</option>
                                                @foreach($categories as $categories)
                                                <option value="{{ $categories->id }}"{{ old('category_id') == $categories->id ? "selected":""}}>
                                                {{ $categories->name}}
                                                </option>
                                                @endforeach
                                            </select>
                                                
                                        
                                        </div>

                                        <hr>    
                                        <!-- Image Field  -->

                                        <input type="file" name="image" id="image" class="form-control-file mb-2" value="{{$item->image}}">
                                    
                                    
                                        <hr> 
                                            <div class="row">   
                                                    <!-- Color Field  -->
                                                        <div class="col-4">
                                                        
                                                                <label for="color" class="row-md-1 col-form-label text-md-right ml-1">{{ ('Color') }}</label> 
                                                    

                                                                <div class="col-12 w-100">
                                                                    <select name="color" id="color" class="form-control">
                                                                        <option value="{{$item->color}}">{{$item->color}}</option> 
                                                                        <option value="/">Not Available </option> 
                                                                        <option value="Blue">Blue </option> 
                                                                        <option value="Light Blue">Light Blue </option> 
                                                                        <option value="Dark Blue">Dark Blue </option> 
                                                                        <option value="Green">Green </option> 
                                                                        <option value="Magenta">Magenta </option> 
                                                                        <option value="Magenta">Red </option> 
                                                                        <option value="Yellow">Yellow </option> 
                                                                        <option value="Magenta">Violet </option> 
                                                                    </select> 
                                                                </div> 
                                                        </div>         
                                                            
                                                    
                                                    <!-- Brand Field -->
                                                        
                                                    <div class="col-4">
                                                                <label for="brand" class="row-md-1 col-form-label text-md-right ml-1">{{ ('Brand') }}</label>    

                                                                <div class="col-12 w-100">
                                                                    <select name="brand" id="brand" class="form-control"> 
                                                                    <option value="{{$item->brand}}">{{$item->brand}}</option> 
                                                                    <option value="Generic">Generic </option> 
                                                                        <option value="Amazon">Amazon </option> 
                                                                        <option value="Speedo">Speedo </option> 
                                                                        <option value="Copozz">Copozz </option> 
                                                                        <option value="Izod">Izod </option> 
                                                                        <option value="Columbia">Columbia </option> 
                                                                        <option value="Smaco">Smaco </option> 
                                                                        <option value="Atomic Aquatics">Atomic Aquatics </option> 
                                                                    </select>
                                                                </div> 
                                                                
                                                            
                                                        </div>   
                                                    
                                                    <!-- Size Field -->
                                                    

                                                    <div class="col-4">
                                                                <label for="size" class="row-md-1 col-form-label text-md-right ml-1">{{ ('Size') }}</label>  
                                                            
                                                                <div class="col-12 w-100">
                                                                    <select name="size" id="size" class="form-control"> 
                                                                    <option value="{{$item->size}}">{{$item->size}}</option> 
                                                                    <option value="All">All </option> 
                                                                    <option value="Adult">Adult </option> 
                                                                    <option value="Kids">Kids </option> 
                                                                    <option value="XL">XL </option> 
                                                                    </select> 
                                                                </div> 
                                                                
                                                                    
                                                    </div>
                                                    
                                                
                                            
                                            </div> 
                                        
                                                <br>    
                                            <button type="submit" class="btn btn-primary">Save Updates</button>      
                                        
                                </div>
                      </form> 
                </div>
                </div> 
                    <div class="col-12 col-md-5">
                        <img src="/storage/{{$item->image}}" alt="image unavailable" class="card-img-top">
                            <div class="card-body">
                                <h3>{{$item->name}}</h3>
                                <p class="card-text">&#8369; {{number_format($item->price,2)}}</p>
                                <p class="card-text">{{ $item->category->name}}</p>
                                <p class="card-text">{{ $item->brand}}</p>
                                <p class="card-text">Color : {{ $item->color}}</p>
                                <p class="card-text">Size  : {{ $item->size}}</p>
                            </div>
                    </div>
            </div>
        </div> 

</div> 


@endsection 

resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card"> 
            @if ($errors->all())
                    <div class="alert alert-danger">
                            <ul>
                                 @foreach ($errors->all() as $error)
                                     <li>{{ $error}}</li>
                                 @endforeach
                            </ul>
                    </div>
                @endif  
              <img src="/public/{{$item->image}}" alt="image unavailable" class="card-img-top">
                     <div class="card-body"> 
                     <form action="{{ route('stocks.store')}}" method="post">
			           @csrf
                     <h3>{{$item->name}}</h3>
                                <p class="card-text">&#8369; {{number_format($item->price,2)}}</p>
                                <p class="card-text">{{ $item->category->name}}</p>
                                <p class="card-text">{{ $item->brand}}</p>
                                <p class="card-text">Color : {{ $item->color}}</p>
                                <p class="card-text">Size  : {{ $item->size}}</p>
                    </div> 

                    <div class="card-footer"> 

                    <a href="{{ route('stocks.index')}}" class="btn btn-outline-primary w-100 mb-2">See Available Stocks</a>
                        @can('isAdmin') 
                    
                      <!-- Item Id -->
                      <label for="item_id" hidden>Item ID</label>
                    <div> 
                    <input type="text" name="item_id" autocomplete="off" class="form-control" mb-2 value="{{ $item->id }}" hidden >  
                    </div>

                       <!-- Name Field -->
                    <label for="name" hidden>Item Name</label>
                    <div> 
                    <input type="text" name="name" autocomplete="off" class="form-control" mb-2 value="{{ $item->name }}" hidden >  
                    </div>
                    
                     <!-- Price Field  -->
                     <label for="price" hidden>Item Price</label>
                    <div>
                    <input type="text" name="price" autocomplete="off" class="form-control" mb-2 value="{{ $item->price }}" hidden>  
                    </div> 
                     
                    <!-- Item Status  -->
                    <label for="status" hidden>Item Status</label>
                    <select name="stat" id="stat" class="form-control" hidden> 
                        <option value="Available">Available </option> 
                        <option value="Not Available">Not Available </option> 
                    </select> 
                    <hr> 
                    <!-- Create New Stock Button   -->
                    <form action="{{ route('stocks.create')}}">
                            <button class="btn btn-warning w-100 mb-2 text-white">Create New Stock</button>
                    </form>
                        <!-- Edit Item  -->
                        <a href="{{ route('items.edit',['item' => $item->id])}}" class="btn btn-outline-warning w-100 mb-2">Edit Item</a>

                        <!-- Delete Item  -->
                        <form action="{{ route('items.destroy',['item' => $item->id])}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-outline-danger w-100 mb-2">Delete</button>
                        </form>
                                
                        @endcan 

                        

            </div>
        </div>
    </div> 
</div> 


@endsection 